version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "3030:3030"
    volumes:
      - sqlite-data:/app/data  # Use a volume for storing SQLite data

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"

volumes:
  sqlite-data:  # Define the SQLite data volume
